[general]
live_config_reload = true
import = ["~/.config/alacritty/e2esound.toml"]

[bell]
duration = 0
animation = "EaseOutExpo"
color = "#404040"

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty-direct"


[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[scrolling]
history = 5000  # tmux使用のため最小限に設定
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 0.92
option_as_alt = "Both"
resize_increments = false
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 50

[window.padding]
x = 5
y = 5

# tmux を併用するためコメントアウト
# [[keyboard.bindings]]
# key = "V"
# mods = "Command"
# action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Command"
# action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

